// Our own school marks: official primary colors (facts) + short monograms.
// We deliberately do not ship universities' trademarked logo files.

export interface SchoolMark {
  color: string;
  mono: string;   // 1–3 letter monogram fallback
  word: string;   // short display wordmark
  domain: string; // official web domain — used to load the school's own favicon
}

export const MARKS: Record<string, SchoolMark> = {
  "Brown":           { color: "#4E3629", mono: "B",   word: "Brown",           domain: "brown.edu" },
  "Carnegie Mellon": { color: "#C41230", mono: "CM",  word: "Carnegie Mellon", domain: "cmu.edu" },
  "Chicago":         { color: "#800000", mono: "Ch",  word: "UChicago",        domain: "uchicago.edu" },
  "Columbia":        { color: "#5A9BD8", mono: "Co",  word: "Columbia",        domain: "columbia.edu" },
  "Cornell":         { color: "#B31B1B", mono: "C",   word: "Cornell",         domain: "cornell.edu" },
  "Dartmouth":       { color: "#00693E", mono: "Da",  word: "Dartmouth",       domain: "dartmouth.edu" },
  "Duke":            { color: "#012169", mono: "D",   word: "Duke",            domain: "duke.edu" },
  "Emory":           { color: "#0C2340", mono: "E",   word: "Emory",           domain: "emory.edu" },
  "Georgetown":      { color: "#041E42", mono: "G",   word: "Georgetown",      domain: "georgetown.edu" },
  "Harvard":         { color: "#A51C30", mono: "H",   word: "Harvard",         domain: "harvard.edu" },
  "Johns Hopkins":   { color: "#002D72", mono: "JH",  word: "Johns Hopkins",   domain: "jhu.edu" },
  "MIT":             { color: "#A31F34", mono: "MIT", word: "MIT",             domain: "mit.edu" },
  "Michigan":        { color: "#00274C", mono: "M",   word: "Michigan",        domain: "umich.edu" },
  "Northwestern":    { color: "#4E2A84", mono: "NU",  word: "Northwestern",    domain: "northwestern.edu" },
  "Notre Dame":      { color: "#0C2340", mono: "ND",  word: "Notre Dame",      domain: "nd.edu" },
  "Princeton":       { color: "#E77500", mono: "P",   word: "Princeton",       domain: "princeton.edu" },
  "Rice":            { color: "#00205B", mono: "R",   word: "Rice",            domain: "rice.edu" },
  "Stanford":        { color: "#8C1515", mono: "S",   word: "Stanford",        domain: "stanford.edu" },
  "UC Berkeley":     { color: "#002676", mono: "Cal", word: "Berkeley",        domain: "berkeley.edu" },
  "UCLA":            { color: "#2774AE", mono: "LA",  word: "UCLA",            domain: "ucla.edu" },
  "UNC":             { color: "#4B9CD3", mono: "NC",  word: "UNC",             domain: "unc.edu" },
  "UPenn":           { color: "#011F5B", mono: "UP",  word: "Penn",            domain: "upenn.edu" },
  "Vanderbilt":      { color: "#866D4B", mono: "V",   word: "Vanderbilt",      domain: "vanderbilt.edu" },
  "Yale":            { color: "#00356B", mono: "Y",   word: "Yale",            domain: "yale.edu" },
  "UC Davis":        { color: "#022851", mono: "D",   word: "UC Davis",        domain: "ucdavis.edu" },
  "UC Irvine":       { color: "#0064A4", mono: "I",   word: "UC Irvine",       domain: "uci.edu" },
  "UC San Diego":    { color: "#00629B", mono: "SD",  word: "UCSD",            domain: "ucsd.edu" },
  "UC Santa Barbara": { color: "#003660", mono: "SB", word: "UCSB",            domain: "ucsb.edu" },
  "UC Santa Cruz":   { color: "#003C6C", mono: "SC",  word: "UCSC",            domain: "ucsc.edu" },
  "UC Riverside":    { color: "#003DA5", mono: "R",   word: "UC Riverside",    domain: "ucr.edu" },
  "UC Merced":       { color: "#005487", mono: "M",   word: "UC Merced",       domain: "ucmerced.edu" },
  "USC":             { color: "#990000", mono: "SC",  word: "USC",             domain: "usc.edu" },
  "NYU":             { color: "#57068C", mono: "NYU", word: "NYU",             domain: "nyu.edu" },
  "WashU":           { color: "#A51417", mono: "WU",  word: "WashU",           domain: "wustl.edu" },
  "UVA":             { color: "#232D4B", mono: "V",   word: "UVA",             domain: "virginia.edu" },
  "Georgia Tech":    { color: "#003057", mono: "GT",  word: "Georgia Tech",    domain: "gatech.edu" },
  "UT Austin":       { color: "#BF5700", mono: "UT",  word: "UT Austin",       domain: "utexas.edu" },
  "Tufts":           { color: "#3E8EDE", mono: "T",   word: "Tufts",           domain: "tufts.edu" },
  "Boston College":  { color: "#8A100B", mono: "BC",  word: "Boston College",  domain: "bc.edu" },
  "Boston University": { color: "#CC0000", mono: "BU", word: "BU",             domain: "bu.edu" },
  "Caltech":         { color: "#FF6C0C", mono: "CT",  word: "Caltech",         domain: "caltech.edu" },
  "Washington":      { color: "#4B2E83", mono: "UW",  word: "UW Seattle",      domain: "washington.edu" },
  "Wisconsin":       { color: "#C5050C", mono: "W",   word: "Wisconsin",       domain: "wisc.edu" },
  "Northeastern":    { color: "#D41B2C", mono: "NU",  word: "Northeastern",    domain: "northeastern.edu" },
  "Purdue":          { color: "#8E6F3E", mono: "P",   word: "Purdue",          domain: "purdue.edu" },
  "Ohio State":      { color: "#BB0000", mono: "OS",  word: "Ohio State",      domain: "osu.edu" },
  "Penn State":      { color: "#041E42", mono: "PS",  word: "Penn State",      domain: "psu.edu" },
  "Maryland":        { color: "#E03A3E", mono: "MD",  word: "Maryland",        domain: "umd.edu" },
  "Illinois":        { color: "#13294B", mono: "IL",  word: "Illinois",        domain: "illinois.edu" },
  "Florida":         { color: "#0021A5", mono: "UF",  word: "Florida",         domain: "ufl.edu" },
  "Texas A&M":       { color: "#500000", mono: "AM",  word: "Texas A&M",       domain: "tamu.edu" },
  "San Diego State": { color: "#A6192E", mono: "SD",  word: "San Diego State", domain: "sdsu.edu" },
  "Cal Poly SLO":    { color: "#154734", mono: "CP",  word: "Cal Poly SLO",    domain: "calpoly.edu" },
  "San Jose State":  { color: "#0055A2", mono: "SJ",  word: "San Jose State",  domain: "sjsu.edu" },
  "Cal State Long Beach": { color: "#1C1C1C", mono: "LB", word: "CSU Long Beach", domain: "csulb.edu" },
  "Cal State Fullerton":  { color: "#00274C", mono: "CF", word: "CSU Fullerton",  domain: "fullerton.edu" },
  "Santa Clara":     { color: "#862633", mono: "SC",  word: "Santa Clara",     domain: "scu.edu" },
  "Fordham":         { color: "#900028", mono: "F",   word: "Fordham",         domain: "fordham.edu" },
  "Villanova":       { color: "#00205B", mono: "V",   word: "Villanova",       domain: "villanova.edu" },
  "Tulane":          { color: "#006747", mono: "T",   word: "Tulane",          domain: "tulane.edu" },
  "Wake Forest":     { color: "#9E7E38", mono: "WF",  word: "Wake Forest",     domain: "wfu.edu" },
  "William & Mary":  { color: "#115740", mono: "WM",  word: "William & Mary",  domain: "wm.edu" },
  "Case Western":    { color: "#0A304E", mono: "CW",  word: "Case Western",    domain: "case.edu" },
  "Rochester":       { color: "#003B71", mono: "R",   word: "Rochester",       domain: "rochester.edu" },
  "Brandeis":        { color: "#003478", mono: "B",   word: "Brandeis",        domain: "brandeis.edu" },
  "UMass Amherst":   { color: "#881C1C", mono: "UM",  word: "UMass Amherst",   domain: "umass.edu" },
  "Rutgers":         { color: "#CC0033", mono: "RU",  word: "Rutgers",         domain: "rutgers.edu" },
  "Pitt":            { color: "#003594", mono: "PT",  word: "Pitt",            domain: "pitt.edu" },
  "Indiana":         { color: "#990000", mono: "IU",  word: "Indiana",         domain: "indiana.edu" },
  "Arizona State":   { color: "#8C1D40", mono: "AS",  word: "Arizona State",   domain: "asu.edu" },
  "Colorado Boulder":{ color: "#565A5C", mono: "CU",  word: "CU Boulder",      domain: "colorado.edu" },
  "Spelman":         { color: "#0F4C81", mono: "SP",  word: "Spelman",         domain: "spelman.edu" },
  "Stony Brook":     { color: "#990000", mono: "SB",  word: "Stony Brook",     domain: "stonybrook.edu" },
  "Binghamton":      { color: "#005A43", mono: "BG",  word: "Binghamton",      domain: "binghamton.edu" },
  "Stevens":         { color: "#A32638", mono: "ST",  word: "Stevens",         domain: "stevens.edu" },
  "Drexel":          { color: "#07294D", mono: "DX",  word: "Drexel",          domain: "drexel.edu" },
  "GWU":             { color: "#033C5A", mono: "GW",  word: "GWU",             domain: "gwu.edu" },
  "RPI":             { color: "#D6001C", mono: "RPI", word: "RPI",             domain: "rpi.edu" },
  "Colorado State":  { color: "#1E4D2B", mono: "CS",  word: "Colorado State",  domain: "colostate.edu" },
  "Buffalo":         { color: "#005BBB", mono: "UB",  word: "Buffalo",         domain: "buffalo.edu" },
  "Marquette":       { color: "#003366", mono: "MQ",  word: "Marquette",       domain: "marquette.edu" },
  "CSU Northridge":  { color: "#CE1126", mono: "NR",  word: "CSU Northridge",  domain: "csun.edu" },
  "Temple":          { color: "#9D2235", mono: "TU",  word: "Temple",          domain: "temple.edu" },
  "Howard":          { color: "#003A63", mono: "HU",  word: "Howard",          domain: "howard.edu" },
  "SMU":             { color: "#0033A0", mono: "SMU", word: "SMU",             domain: "smu.edu" },
  "TCU":             { color: "#4D1979", mono: "TCU", word: "TCU",             domain: "tcu.edu" },
  "Oregon State":    { color: "#DC4405", mono: "OS",  word: "Oregon State",    domain: "oregonstate.edu" },
  "Cal State San Marcos": { color: "#00558C", mono: "SM", word: "CSU San Marcos", domain: "csusm.edu" },
  "Baylor":          { color: "#154734", mono: "BU",  word: "Baylor",          domain: "baylor.edu" },
  "American":        { color: "#C41230", mono: "AU",  word: "American",        domain: "american.edu" },
  "Sacramento State":{ color: "#043927", mono: "SA",  word: "Sacramento State", domain: "csus.edu" },
  "Lehigh":          { color: "#653819", mono: "LU",  word: "Lehigh",          domain: "lehigh.edu" },
  "NC State":        { color: "#CC0000", mono: "NC",  word: "NC State",        domain: "ncsu.edu" },
  "Alabama":         { color: "#9E1B32", mono: "AL",  word: "Alabama",         domain: "ua.edu" },
  "Nebraska":        { color: "#E41C38", mono: "NE",  word: "Nebraska",        domain: "unl.edu" },
  "Minnesota Twin Cities": { color: "#7A0019", mono: "MN", word: "Minnesota",  domain: "umn.edu" },
  "Pepperdine":      { color: "#00205B", mono: "PP",  word: "Pepperdine",      domain: "pepperdine.edu" },
  "Loyola Marymount":{ color: "#00205B", mono: "LMU", word: "LMU",             domain: "lmu.edu" },
  "Delaware":        { color: "#00539F", mono: "DE",  word: "Delaware",        domain: "udel.edu" },
  "Oklahoma":        { color: "#841617", mono: "OU",  word: "Oklahoma",        domain: "ou.edu" },
  "Clemson":         { color: "#F66733", mono: "CL",  word: "Clemson",         domain: "clemson.edu" },
  "Auburn":          { color: "#0C2340", mono: "AU",  word: "Auburn",          domain: "auburn.edu" },
  "Georgia":         { color: "#BA0C2F", mono: "UGA", word: "Georgia",         domain: "uga.edu" },
  "Arizona":         { color: "#0C234B", mono: "AZ",  word: "Arizona",         domain: "arizona.edu" },
  "South Carolina":  { color: "#73000A", mono: "SC",  word: "South Carolina",  domain: "sc.edu" },
  "UConn":           { color: "#000E2F", mono: "UC",  word: "UConn",           domain: "uconn.edu" },
  "Oregon":          { color: "#154733", mono: "OR",  word: "Oregon",          domain: "uoregon.edu" },
  "Iowa":            { color: "#FFCD00", mono: "IA",  word: "Iowa",            domain: "uiowa.edu" },
  "Washington State":{ color: "#981E32", mono: "WS",  word: "Washington State", domain: "wsu.edu" },
  "Michigan State":  { color: "#18453B", mono: "MS",  word: "Michigan State",  domain: "msu.edu" },
  "Iowa State":      { color: "#C8102E", mono: "IS",  word: "Iowa State",      domain: "iastate.edu" },
  "Kansas":          { color: "#0051BA", mono: "KU",  word: "Kansas",          domain: "ku.edu" },
  "Utah":            { color: "#CC0000", mono: "UT",  word: "Utah",            domain: "utah.edu" },
  "Tennessee":       { color: "#FF8200", mono: "TN",  word: "Tennessee",       domain: "utk.edu" },
  "Cal Poly Pomona": { color: "#1B4332", mono: "CP",  word: "Cal Poly Pomona", domain: "cpp.edu" },
  "Chico State":     { color: "#B5121B", mono: "CH",  word: "Chico State",     domain: "csuchico.edu" },
  "Queens College (CUNY)": { color: "#003DA5", mono: "QC", word: "Queens College", domain: "qc.cuny.edu" },
  "Syracuse":        { color: "#F76900", mono: "SU",  word: "Syracuse",        domain: "syracuse.edu" },
  "City College (CUNY)":   { color: "#003087", mono: "CC", word: "CCNY",         domain: "ccny.cuny.edu" },
  "Virginia Tech":   { color: "#630031", mono: "VT",  word: "Virginia Tech",   domain: "vt.edu" },
  "Baruch":          { color: "#5B2E8C", mono: "BC",  word: "Baruch",          domain: "baruch.cuny.edu" },
  "Sonoma State":    { color: "#00543C", mono: "SS",  word: "Sonoma State",    domain: "sonoma.edu" },
  "SUNY Albany":     { color: "#461D7C", mono: "AL",  word: "SUNY Albany",     domain: "albany.edu" },
  "Mizzou":          { color: "#F1B82D", mono: "MZ",  word: "Mizzou",          domain: "missouri.edu" },
  "SUNY Geneseo":    { color: "#54585A", mono: "GN",  word: "SUNY Geneseo",    domain: "geneseo.edu" },
  "James Madison":   { color: "#450084", mono: "JM",  word: "James Madison",  domain: "jmu.edu" },
  "SF State":        { color: "#231161", mono: "SF",  word: "SF State",       domain: "sfsu.edu" },
  "Rowan":           { color: "#000000", mono: "RW",  word: "Rowan",          domain: "rowan.edu" },
  "Montclair State": { color: "#003C71", mono: "MS",  word: "Montclair State", domain: "montclair.edu" },
  "CSU Channel Islands": { color: "#00549F", mono: "CI", word: "CSU Channel Islands", domain: "csuci.edu" },
  "George Mason":    { color: "#006633", mono: "GM",  word: "George Mason",   domain: "gmu.edu" },
  "Cal State San Bernardino": { color: "#003DA5", mono: "SB", word: "CSU San Bernardino", domain: "csusb.edu" },
  "Cal Poly Humboldt": { color: "#00573F", mono: "HU", word: "Cal Poly Humboldt", domain: "humboldt.edu" },
  "Cal State LA":    { color: "#FFD100", mono: "LA",  word: "Cal State LA",   domain: "calstatela.edu" },
  "Cal State Dominguez Hills": { color: "#00274C", mono: "DH", word: "CSU Dominguez Hills", domain: "csudh.edu" },
  "CSU Monterey Bay": { color: "#004B8D", mono: "MB", word: "CSU Monterey Bay", domain: "csumb.edu" },
  "Amherst":         { color: "#5B1414", mono: "AC",  word: "Amherst",         domain: "amherst.edu" },
  "Williams":        { color: "#500082", mono: "WC",  word: "Williams",        domain: "williams.edu" },
  "Swarthmore":      { color: "#B32B2B", mono: "SW",  word: "Swarthmore",      domain: "swarthmore.edu" },
  "Pomona College":  { color: "#00447C", mono: "PC",  word: "Pomona",          domain: "pomona.edu" },
  "Claremont McKenna": { color: "#8A1538", mono: "CM", word: "Claremont McKenna", domain: "cmc.edu" },
  "Harvey Mudd":     { color: "#EF7D00", mono: "HM",  word: "Harvey Mudd",     domain: "hmc.edu" },
  "Wesleyan":        { color: "#B41F30", mono: "WU",  word: "Wesleyan",        domain: "wesleyan.edu" },
  "Middlebury":      { color: "#00205B", mono: "MC",  word: "Middlebury",      domain: "middlebury.edu" },
  "Bowdoin":         { color: "#000000", mono: "BC",  word: "Bowdoin",         domain: "bowdoin.edu" },
  "Bates":           { color: "#7B1F3A", mono: "BT",  word: "Bates",           domain: "bates.edu" },
  "Hamilton College": { color: "#00509D", mono: "HC", word: "Hamilton",        domain: "hamilton.edu" },
  "Vassar":          { color: "#E2231A", mono: "VC",  word: "Vassar",          domain: "vassar.edu" },
  "Barnard":         { color: "#00A0DC", mono: "BN",  word: "Barnard",         domain: "barnard.edu" },
  "Colgate":         { color: "#821019", mono: "CU",  word: "Colgate",         domain: "colgate.edu" },
  "Bucknell":         { color: "#FF6600", mono: "BK", word: "Bucknell",        domain: "bucknell.edu" },
  "Richmond":        { color: "#002554", mono: "UR",  word: "Richmond",        domain: "richmond.edu" },
  "Davidson":        { color: "#A6192E", mono: "DC",  word: "Davidson",        domain: "davidson.edu" },
  "Washington and Lee": { color: "#001B3F", mono: "WL", word: "Washington and Lee", domain: "wlu.edu" },
  "Grinnell":        { color: "#B01E24", mono: "GC",  word: "Grinnell",        domain: "grinnell.edu" },
  "Carleton":        { color: "#005696", mono: "CC",  word: "Carleton",        domain: "carleton.edu" },
  "Macalester":      { color: "#002E5D", mono: "MA",  word: "Macalester",      domain: "macalester.edu" },
  "Oberlin":         { color: "#B90E31", mono: "OC",  word: "Oberlin",         domain: "oberlin.edu" },
  "Kenyon":          { color: "#5D3754", mono: "KC",  word: "Kenyon",          domain: "kenyon.edu" },
  "Smith":           { color: "#003F87", mono: "SC",  word: "Smith",           domain: "smith.edu" },
  "Mount Holyoke":   { color: "#003057", mono: "MH",  word: "Mount Holyoke",   domain: "mtholyoke.edu" },
  "Occidental":      { color: "#000000", mono: "OX",  word: "Occidental",      domain: "oxy.edu" },
  "Scripps":         { color: "#FFAA00", mono: "SP",  word: "Scripps",         domain: "scrippscollege.edu" },
  "Fairfield University": { color: "#E4002B", mono: "FU", word: "Fairfield",  domain: "fairfield.edu" },
  "Rhodes College":  { color: "#000000", mono: "RC",  word: "Rhodes",          domain: "rhodes.edu" },
  "Denison University": { color: "#B22234", mono: "DU", word: "Denison",       domain: "denison.edu" },
  "Furman University": { color: "#590A2A", mono: "FU", word: "Furman",         domain: "furman.edu" },
  "Trinity College (Connecticut)": { color: "#00205B", mono: "TC", word: "Trinity College", domain: "trincoll.edu" },
  "Union College":   { color: "#651D32", mono: "UC",  word: "Union College",   domain: "union.edu" },
  "Skidmore College": { color: "#4A7729", mono: "SK", word: "Skidmore",        domain: "skidmore.edu" },
  "Loyola University Maryland": { color: "#914E1E", mono: "LM", word: "Loyola Maryland", domain: "loyola.edu" },
  "Loyola Chicago":  { color: "#9E1B32", mono: "LC",  word: "Loyola Chicago",  domain: "luc.edu" },
  "University of San Francisco": { color: "#00543D", mono: "SF", word: "USF",  domain: "usfca.edu" },
  "Elon University": { color: "#552B85", mono: "EL",  word: "Elon",            domain: "elon.edu" },
  "Providence College": { color: "#000000", mono: "PC", word: "Providence",    domain: "providence.edu" },
  "DePaul":          { color: "#0057B8", mono: "DP",  word: "DePaul",          domain: "depaul.edu" },
  "University of San Diego": { color: "#003B71", mono: "SD", word: "USD",      domain: "sandiego.edu" },
  "University of Denver": { color: "#8B2332", mono: "DU", word: "Denver",      domain: "du.edu" },
  "Cal State Bakersfield": { color: "#003594", mono: "BK", word: "CSU Bakersfield", domain: "csub.edu" },
  "Xavier University": { color: "#000066", mono: "XU", word: "Xavier",         domain: "xavier.edu" },
  "Creighton":       { color: "#00287A", mono: "CU",  word: "Creighton",       domain: "creighton.edu" },

  "VCU":             { color: "#F6BE00", mono: "VC",  word: "VCU",             domain: "vcu.edu" },
  "Old Dominion":    { color: "#003057", mono: "OD",  word: "Old Dominion",    domain: "odu.edu" },
  "Towson":          { color: "#FDB515", mono: "TU",  word: "Towson",          domain: "towson.edu" },
  "Kennesaw State":  { color: "#000000", mono: "KS",  word: "Kennesaw State",  domain: "kennesaw.edu" },
  "Georgia State":   { color: "#0039A6", mono: "GS",  word: "Georgia State",   domain: "gsu.edu" },
  "University of North Texas": { color: "#00853E", mono: "NT", word: "UNT",    domain: "unt.edu" },
  "Texas Tech":      { color: "#CC0000", mono: "TT",  word: "Texas Tech",      domain: "ttu.edu" },
  "Texas State":     { color: "#501214", mono: "TS",  word: "Texas State",     domain: "txstate.edu" },
  "University of Houston": { color: "#C8102E", mono: "UH", word: "Houston",    domain: "uh.edu" },
  "University of Texas at Dallas": { color: "#154734", mono: "TD", word: "UT Dallas", domain: "utdallas.edu" },
  "Miami University (Ohio)": { color: "#C41230", mono: "MU", word: "Miami (OH)", domain: "miamioh.edu" },
  "Bowling Green State University": { color: "#4F2D7F", mono: "BG", word: "Bowling Green", domain: "bgsu.edu" },
  "Kent State":      { color: "#002664", mono: "KT",  word: "Kent State",      domain: "kent.edu" },
  "Cleveland State": { color: "#00843D", mono: "CS",  word: "Cleveland State", domain: "csuohio.edu" },
  "West Virginia University": { color: "#EAAA00", mono: "WV", word: "West Virginia", domain: "wvu.edu" },
  "Louisville":      { color: "#AD0000", mono: "LV",  word: "Louisville",      domain: "louisville.edu" },
  "Kentucky":        { color: "#0033A0", mono: "UK",  word: "Kentucky",        domain: "uky.edu" },
  "Cincinnati":      { color: "#E00122", mono: "UC",  word: "Cincinnati",      domain: "uc.edu" },
  "UNC Charlotte":   { color: "#005035", mono: "CH",  word: "UNC Charlotte",   domain: "charlotte.edu" },
  "East Carolina":   { color: "#592A8A", mono: "EC",  word: "East Carolina",   domain: "ecu.edu" },
  "Appalachian State": { color: "#222222", mono: "AP", word: "App State",      domain: "appstate.edu" },
  "Mississippi State": { color: "#660000", mono: "MS", word: "Mississippi State", domain: "msstate.edu" },
  "Ole Miss":        { color: "#14213D", mono: "OM",  word: "Ole Miss",        domain: "olemiss.edu" },
  "Louisiana State": { color: "#461D7C", mono: "LS",  word: "LSU",             domain: "lsu.edu" },
  "Arkansas":        { color: "#9D2235", mono: "AR",  word: "Arkansas",        domain: "uark.edu" },
  "New Mexico":      { color: "#BA0C2F", mono: "NM",  word: "New Mexico",      domain: "unm.edu" },
  "Nevada Las Vegas": { color: "#CF0A2C", mono: "UN", word: "UNLV",            domain: "unlv.edu" },
};

export function logoUrl(name: string, size = 64): string {
  return `https://www.google.com/s2/favicons?domain=${markOf(name).domain}&sz=${size}`;
}

export function markOf(name: string): SchoolMark {
  return MARKS[name] ?? { color: "#55575c", mono: name.slice(0, 2), word: name };
}
